services:
  - type: web
    name: sentiment-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host=0.0.0.0 --port=$PORT
    runtime: python
    pythonVersion: 3.10.13
    autoDeploy: true
    region: oregon
